BethanysPieShop/Controllers/PieController.cs
using BethanysPieShop.Models;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BethanysPieShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository pieRepository;
        private readonly ICategoryRepository categoryRepository;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            this.pieRepository = pieRepository;
            this.categoryRepository = categoryRepository;
        }

        public IActionResult List (string category)
        {
            PiesListViewModel piesListViewModel = new PiesListViewModel();

            piesListViewModel.Pies = pieRepository.AllPies.Where(p => string.IsNullOrEmpty(category) || p.Category.CategoryName.Equals(category));
            piesListViewModel.CurrentCategory = string.IsNullOrEmpty(category) ? "All Pies" : $"Pies of category <{category}>";

            return View(piesListViewModel);
        }

        public IActionResult Details(int id)
        {
            Pie pie = pieRepository.GetPieById(id);
            return View(pie);
        }
    }
}

BethanysPieShop/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

@if (Model.Count<Category>() > 2)
{
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"
           asp-controller="Pie" asp-action="List">
            Pies
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            @foreach (var category in Model)
            {
                <li>
                    <a class="dropdown-item"
                       asp-controller="Pie"
                       asp-action="List"
                       asp-route-category="@category.CategoryName">@category.CategoryName</a>
                </li>
            }
            <li><hr class="dropdown-divider"></li>
            <li>
                <a class="dropdown-item"
                   asp-controller="Pie"
                   asp-action="List">All Pies</a>
            </li>
        </ul>
    </li>
}
else
{
    <li class="nav-item">
        <a asp-controller="Pie" asp-action="List" class="nav-link">Pies</a>
    </li>
}